name: kfd-automation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make IPA
        run: |
          xcodebuild clean build -project kfd.xcodeproj \
            -scheme kfd \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0'
      - uses: actions/upload-artifact@v3
        with:
          name: IPA Download
          path: mute-cam/kfd.ipa
